// Generated by CoffeeScript 1.7.1
(function() {
  var Q, arrayTemplate, objectTemplate, template, _;

  Q = require('q');

  _ = require('lodash');

  template = function(templateLiteral) {
    if (_.isArray(templateLiteral)) {
      return arrayTemplate(templateLiteral);
    } else if (_.isObject(templateLiteral)) {
      return objectTemplate(templateLiteral);
    } else {
      throw new Error('unsupported template type');
    }
  };

  arrayTemplate = function(arrayTemplateLiteral) {
    var attrs, objDef, tmpl;
    objDef = _.first(arrayTemplateLiteral);
    attrs = Object.keys(objDef);
    tmpl = objectTemplate(objDef);
    return function(arrayOrPromise) {
      return Q(arrayOrPromise).then(function(array) {
        return Q.all(array.map(function(item) {
          return tmpl(item);
        }));
      });
    };
  };

  objectTemplate = function(objectTemplateLiteral) {
    return function(objOrPromise) {
      return Q(objOrPromise).then(function(obj) {
        return Object.keys(objectTemplateLiteral).reduce(function(newObj, attr) {
          newObj[attr] = objectTemplateLiteral[attr].call(obj);
          return newObj;
        }, {});
      });
    };
  };

  (typeof module !== "undefined" && module !== null ? module.exports.template = template : void 0) || (this.template = template);

}).call(this);
